// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hcjcoixaemmhttadawfc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhjamNvaXhhZW1taHR0YWRhd2ZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NzA0NTYsImV4cCI6MjA2MDI0NjQ1Nn0.lM-GNc2ElLFtj5-KHibPiIhU0Quk6VE7-J1O6ynCuEk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);